import * as vscode from 'vscode';
import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { logInfo } from './utils';

/**
 * MonitorHookServer
 * -----------------
 * A tiny loopback HTTP server that Claude Code hooks "poke" after every tool
 * use / prompt / stop. The poke is only a signal — the monitor re-reads the
 * transcript incrementally when it fires, giving near-instant updates without
 * depending on filesystem-watch latency.
 *
 * Layout on disk (under ~/.claude):
 *   dyno-monitor.port   - the bound port (so the hook knows where to POST)
 *   dyno-monitor-hook.js - the hook script Claude executes
 */

const PORT_RANGE_START = 37100;
const PORT_RANGE_END = 37120;

function claudeHome(): string { return path.join(os.homedir(), '.claude'); }
function portFile(): string { return path.join(claudeHome(), 'dyno-monitor.port'); }
export function hookScriptPath(): string { return path.join(claudeHome(), 'dyno-monitor-hook.js'); }

const HOOK_SCRIPT = `#!/usr/bin/env node
// Auto-generated by Dyno Extension - Claude Task Monitor. Safe to delete.
const fs=require('fs'),http=require('http'),os=require('os'),path=require('path');
let port=0;
try{ port=parseInt(fs.readFileSync(path.join(os.homedir(),'.claude','dyno-monitor.port'),'utf8').trim(),10); }catch(e){}
// drain stdin so Claude Code isn't blocked, then exit quickly
try{ process.stdin.resume(); process.stdin.on('data',()=>{}); process.stdin.on('error',()=>{}); }catch(e){}
function done(){ try{process.exit(0);}catch(e){} }
if(port){
  try{
    const req=http.request({host:'127.0.0.1',port,path:'/poke',method:'POST',timeout:400}, done);
    req.on('error',done); req.on('timeout',done); req.end();
  }catch(e){ done(); }
}
setTimeout(done, 600);
`;

export class MonitorHookServer {
    private server: http.Server | undefined;
    private port = 0;
    private lastPoke = 0;
    private emitter = new vscode.EventEmitter<void>();

    readonly onPoke = this.emitter.event;

    isConnected(): boolean {
        return this.lastPoke > 0 && Date.now() - this.lastPoke < 5 * 60 * 1000;
    }
    getPort(): number { return this.port; }

    start() {
        if (this.server) { return; }
        this.writeHookScript();
        this.tryListen(PORT_RANGE_START);
    }

    private tryListen(port: number) {
        if (port > PORT_RANGE_END) { logInfo('Claude Monitor: no free port for hook server'); return; }
        const server = http.createServer((req, res) => {
            if (req.method === 'POST' && req.url === '/poke') {
                this.lastPoke = Date.now();
                // drain and respond
                req.on('data', () => { /* discard */ });
                req.on('end', () => { res.writeHead(204); res.end(); this.emitter.fire(); });
                req.on('error', () => { try { res.end(); } catch { /* */ } });
            } else {
                res.writeHead(404); res.end();
            }
        });
        server.on('error', (err: any) => {
            if (err?.code === 'EADDRINUSE') { this.tryListen(port + 1); }
            else { logInfo(`Claude Monitor hook server error: ${err?.message}`); }
        });
        server.listen(port, '127.0.0.1', () => {
            this.server = server;
            this.port = port;
            try { fs.writeFileSync(portFile(), String(port), 'utf8'); } catch { /* */ }
            logInfo(`Claude Monitor hook server listening on 127.0.0.1:${port}`);
        });
    }

    private writeHookScript() {
        try {
            fs.mkdirSync(claudeHome(), { recursive: true });
            fs.writeFileSync(hookScriptPath(), HOOK_SCRIPT, 'utf8');
        } catch (e) { logInfo(`Claude Monitor: cannot write hook script: ${(e as Error).message}`); }
    }

    stop() {
        this.server?.close();
        this.server = undefined;
        this.emitter.dispose();
    }
}

// ---------------------------------------------------------------------------
// Installing the hook into a workspace's .claude/settings.json
// ---------------------------------------------------------------------------

const HOOK_EVENTS = ['PostToolUse', 'UserPromptSubmit', 'Stop'] as const;
const HOOK_MARK = 'dyno-monitor-hook.js';

function hookCommand(): string {
    // JSON string will escape backslashes on Windows paths correctly via JSON.stringify at write time
    return `node "${hookScriptPath()}"`;
}

/** Merge the monitor hooks into <workspace>/.claude/settings.json without
 *  clobbering existing hooks. Returns a human-readable result message. */
export async function installMonitorHook(cwd: string): Promise<string> {
    const dir = path.join(cwd, '.claude');
    const file = path.join(dir, 'settings.json');
    let settings: any = {};
    let existed = false;
    try {
        const raw = fs.readFileSync(file, 'utf8');
        settings = JSON.parse(raw);
        existed = true;
    } catch { settings = {}; }

    if (typeof settings !== 'object' || settings === null) { settings = {}; }
    if (!settings.hooks || typeof settings.hooks !== 'object') { settings.hooks = {}; }

    const cmd = hookCommand();
    let added = 0;

    for (const evt of HOOK_EVENTS) {
        const arr: any[] = Array.isArray(settings.hooks[evt]) ? settings.hooks[evt] : [];
        // already installed?
        const already = JSON.stringify(arr).includes(HOOK_MARK);
        if (already) { settings.hooks[evt] = arr; continue; }
        const entry: any = { hooks: [{ type: 'command', command: cmd }] };
        if (evt === 'PostToolUse') { entry.matcher = '*'; }
        arr.push(entry);
        settings.hooks[evt] = arr;
        added++;
    }

    if (added === 0) { return 'Claude Monitor hook already installed for this workspace.'; }

    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(file, JSON.stringify(settings, null, 2) + '\n', 'utf8');
    return `${existed ? 'Updated' : 'Created'} ${path.relative(cwd, file)} — live hook installed (${added} events). Restart the Claude Code session to activate.`;
}

/** Remove the monitor hooks from a workspace's settings.json. */
export async function uninstallMonitorHook(cwd: string): Promise<string> {
    const file = path.join(cwd, '.claude', 'settings.json');
    let settings: any;
    try { settings = JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return 'No .claude/settings.json found.'; }
    if (!settings?.hooks) { return 'No hooks to remove.'; }
    let removed = 0;
    for (const evt of HOOK_EVENTS) {
        const arr = settings.hooks[evt];
        if (!Array.isArray(arr)) { continue; }
        const kept = arr.filter((e: any) => !JSON.stringify(e).includes(HOOK_MARK));
        removed += arr.length - kept.length;
        if (kept.length) { settings.hooks[evt] = kept; } else { delete settings.hooks[evt]; }
    }
    if (Object.keys(settings.hooks).length === 0) { delete settings.hooks; }
    fs.writeFileSync(file, JSON.stringify(settings, null, 2) + '\n', 'utf8');
    return `Removed ${removed} monitor hook entr${removed === 1 ? 'y' : 'ies'}.`;
}
